### PR TITLE
Change search to use a lowercase search term and wildcards.

### PR DESCRIPTION
**Pull request by r15ch13**
Now it is possible to search for "ipod" instead of "iPod". And searching for "ipc" will get you "iPod Classic".

### CODE REVIEW

**Comment by bgultekin** [comment]
Hi,

Thanks for your cooperation. It is very helpful. But I don't really understand what is the aim of the this commit. 
If I am not mistaken, It is already possible to search with uppercase letters and getting results with lowercase letters and also vice-versa as you specified in your description.

**Comment by r15ch13** [comment]
Hi, 

Oh i tested it on a database with utf8_bin collation. So LIKE was case senitive. Your version works with the standard latin1_swedish_ci collation. Didn't see that ...

**Comment by bgultekin** [comment]
I am using it with utf8_general_ci which is case insensitive. I missed it. You're right in a sense but I think it is not neccessary to force developer to use case insensitive or case sensitive searching. 

Maybe, this feature can be developed as an option (not default) ?

**Comment by r15ch13** [comment]
Something like that?

**Comment by bgultekin** [comment]
That's better :) thanks a lot. 
Lastly, sorry about late reply.

**Pull request merged**
